package validations

import (
	"fmt"

	"github.com/hashicorp/go-cty/cty"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
)

var (
	smileCdrUserPermissionTypes = map[string]bool{
		"ACCESS_ADMIN_JSON":                               true,
		"ACCESS_ADMIN_WEB":                                true,
		"ACCESS_FHIRWEB":                                  true,
		"ACCESS_FHIR_ENDPOINT":                            true,
		"AG_ADMIN_CONSOLE_READ":                           true,
		"AG_ADMIN_CONSOLE_WRITE":                          true,
		"AG_DEV_PORTAL_READ":                              true,
		"AG_DEV_PORTAL_WRITE":                             true,
		"ARCHIVE_MODULE":                                  true,
		"BLOCK_FHIR_READ_UNLESS_CODE_IN_VS":               true,
		"BLOCK_FHIR_READ_UNLESS_CODE_NOT_IN_VS":           true,
		"CDA_IMPORT":                                      true,
		"CHANGE_OWN_DEFAULT_LAUNCH_CONTEXTS":              true,
		"CHANGE_OWN_PASSWORD":                             true,
		"CHANGE_OWN_TFA_KEY":                              true,
		"CONTROL_MODULE":                                  true,
		"CREATE_CDA_TEMPLATE":                             true,
		"CREATE_MODULE":                                   true,
		"CREATE_USER":                                     true,
		"DELETE_CDA_TEMPLATE":                             true,
		"DOCREF":                                          true,
		"DQM_QPP_BUILD":                                   true,
		"EMPI_ADMIN":                                      true,
		"EMPI_UPDATE_MATCH_RULES":                         true,
		"EMPI_VIEW_MATCH_RULES":                           true,
		"ETL_IMPORT_PROCESS_FILE":                         true,
		"FHIR_ACCESS_PARTITION_ALL":                       true,
		"FHIR_ACCESS_PARTITION_NAME":                      true,
		"FHIR_ALL_DELETE":                                 true,
		"FHIR_ALL_READ":                                   true,
		"FHIR_ALL_WRITE":                                  true,
		"FHIR_AUTO_MDM":                                   true,
		"FHIR_BATCH":                                      true,
		"FHIR_CAPABILITIES":                               true,
		"FHIR_DELETE_ALL_IN_COMPARTMENT":                  true,
		"FHIR_DELETE_ALL_OF_TYPE":                         true,
		"FHIR_DELETE_CASCADE_ALLOWED":                     true,
		"FHIR_DELETE_EXPUNGE":                             true,
		"FHIR_DELETE_TYPE_IN_COMPARTMENT":                 true,
		"FHIR_DTR_USER":                                   true,
		"FHIR_EMPI_ADMIN":                                 true,
		"FHIR_EXPUNGE_DELETED":                            true,
		"FHIR_EXPUNGE_EVERYTHING":                         true,
		"FHIR_EXPUNGE_PREVIOUS_VERSIONS":                  true,
		"FHIR_EXTENDED_OPERATION_ON_ANY_INSTANCE":         true,
		"FHIR_EXTENDED_OPERATION_ON_ANY_INSTANCE_OF_TYPE": true,
		"FHIR_EXTENDED_OPERATION_ON_SERVER":               true,
		"FHIR_EXTENDED_OPERATION_ON_TYPE":                 true,
		"FHIR_GET_RESOURCE_COUNTS":                        true,
		"FHIR_GRAPHQL":                                    true,
		"FHIR_LIVEBUNDLE":                                 true,
		"FHIR_MANAGE_PARTITIONS":                          true,
		"FHIR_MANUAL_VALIDATION":                          true,
		"FHIR_MDM_ADMIN":                                  true,
		"FHIR_META_OPERATIONS_SUPERUSER":                  true,
		"FHIR_MODIFY_SEARCH_PARAMETERS":                   true,
		"FHIR_OP_APPLY":                                   true,
		"FHIR_OP_BINARY_ACCESS_READ":                      true,
		"FHIR_OP_BINARY_ACCESS_WRITE":                     true,
		"FHIR_OP_CQL_EVALUATE_MEASURE":                    true,
		"FHIR_OP_EMPI_CLEAR":                              true,
		"FHIR_OP_EMPI_DUPLICATE_PERSONS":                  true,
		"FHIR_OP_EMPI_MERGE_PERSONS":                      true,
		"FHIR_OP_EMPI_QUERY_LINKS":                        true,
		"FHIR_OP_EMPI_SUBMIT":                             true,
		"FHIR_OP_EMPI_UPDATE_LINK":                        true,
		"FHIR_OP_ENCOUNTER_EVERYTHING":                    true,
		"FHIR_OP_EXTRACT":                                 true,
		"FHIR_OP_INITIATE_BULK_DATA_EXPORT":               true,
		"FHIR_OP_INITIATE_BULK_DATA_EXPORT_GROUP":         true,
		"FHIR_OP_INITIATE_BULK_DATA_EXPORT_PATIENT":       true,
		"FHIR_OP_INITIATE_BULK_DATA_EXPORT_SYSTEM":        true,
		"FHIR_OP_INITIATE_BULK_DATA_IMPORT":               true,
		"FHIR_OP_MDM_CLEAR":                               true,
		"FHIR_OP_MDM_CREATE_LINK":                         true,
		"FHIR_OP_MDM_DUPLICATE_GOLDEN_RESOURCES":          true,
		"FHIR_OP_MDM_LINK_HISTORY":                        true,
		"FHIR_OP_MDM_MERGE_GOLDEN_RESOURCES":              true,
		"FHIR_OP_MDM_NOT_DUPLICATE":                       true,
		"FHIR_OP_MDM_QUERY_LINKS":                         true,
		"FHIR_OP_MDM_SUBMIT":                              true,
		"FHIR_OP_MDM_UPDATE_LINK":                         true,
		"FHIR_OP_MEMBER_MATCH":                            true,
		"FHIR_OP_PACKAGE":                                 true,
		"FHIR_OP_PATIENT_EVERYTHING":                      true,
		"FHIR_OP_PATIENT_MATCH":                           true,
		"FHIR_OP_PATIENT_SUMMARY":                         true,
		"FHIR_OP_POPULATE":                                true,
		"FHIR_OP_PREPOPULATE":                             true,
		"FHIR_OP_STRUCTUREDEFINITION_SNAPSHOT":            true,
		"FHIR_PATCH":                                      true,
		"FHIR_PROCESS_MESSAGE":                            true,
		"FHIR_READ_ALL_IN_COMPARTMENT":                    true,
		"FHIR_READ_ALL_OF_TYPE":                           true,
		"FHIR_READ_INSTANCE":                              true,
		"FHIR_READ_SEARCH_PARAMETERS":                     true,
		"FHIR_READ_TYPE_IN_COMPARTMENT":                   true,
		"FHIR_TRANSACTION":                                true,
		"FHIR_TRIGGER_SUBSCRIPTION":                       true,
		"FHIR_UPDATE_REWRITE_HISTORY":                     true,
		"FHIR_UPLOAD_EXTERNAL_TERMINOLOGY":                true,
		"FHIR_WRITE_ALL_IN_COMPARTMENT":                   true,
		"FHIR_WRITE_ALL_OF_TYPE":                          true,
		"FHIR_WRITE_INSTANCE":                             true,
		"FHIR_WRITE_TYPE_IN_COMPARTMENT":                  true,
		"INVOKE_CDS_HOOKS":                                true,
		"MANAGE_BATCH_JOBS":                               true,
		"MDM_ADMIN":                                       true,
		"MDM_UPDATE_MATCH_RULES":                          true,
		"MDM_VIEW_MATCH_RULES":                            true,
		"MODULE_ADMIN":                                    true,
		"OIDC_CLIENT_PRESET_PERMISSION":                   true,
		"OPENID_CONNECT_ADD_CLIENT":                       true,
		"OPENID_CONNECT_ADD_SERVER":                       true,
		"OPENID_CONNECT_EDIT_CLIENT":                      true,
		"OPENID_CONNECT_EDIT_SERVER":                      true,
		"OPENID_CONNECT_MANAGE_GLOBAL_SESSIONS":           true,
		"OPENID_CONNECT_VIEW_CLIENT_LIST":                 true,
		"OPENID_CONNECT_VIEW_SERVER_LIST":                 true,
		"PACKAGE_REGISTRY_READ":                           true,
		"PACKAGE_REGISTRY_WRITE":                          true,
		"REINSTATE_MODULE":                                true,
		"ROLE_ANONYMOUS":                                  true,
		"ROLE_FHIR_CLIENT":                                true,
		"ROLE_FHIR_CLIENT_SUPERUSER":                      true,
		"ROLE_FHIR_CLIENT_SUPERUSER_RO":                   true,
		"ROLE_FHIR_TERMINOLOGY_READ_CLIENT":               true,
		"ROLE_SUPERUSER":                                  true,
		"ROLE_SYSTEM":                                     true,
		"ROLE_SYSTEM_INITIALIZATION":                      true,
		"SAVE_USER":                                       true,
		"START_STOP_MODULE":                               true,
		"SUBMIT_ATTACHMENT":                               true,
		"UPDATE_MODULE_CONFIG":                            true,
		"UPDATE_USER":                                     true,
		"USE_CDA_TEMPLATE":                                true,
		"VIEW_AUDIT_LOG":                                  true,
		"VIEW_BATCH_JOBS":                                 true,
		"VIEW_CDA_TEMPLATE":                               true,
		"VIEW_METRICS":                                    true,
		"VIEW_MODULE_CONFIG":                              true,
		"VIEW_MODULE_STATUS":                              true,
		"VIEW_TRANSACTION_LOG":                            true,
		"VIEW_TRANSACTION_LOG_EVENT":                      true,
		"VIEW_USERS":                                      true,
	}
)

func IsUserPermission(i interface{}, k cty.Path) diag.Diagnostics {

	// Convert the input value to a string (assuming the input is a string)
	inputValue, ok := i.(string)
	if !ok {
		return diag.Diagnostics{
			diag.Diagnostic{
				Severity: diag.Error,
				Summary:  "Invalid type for the field",
				Detail:   fmt.Sprintf("Expected a string, but got %T", i),
			},
		}
	}
	// Check if the value is in the set of acceptable values
	if _, ok := smileCdrUserPermissionTypes[inputValue]; !ok {
		return diag.Diagnostics{
			diag.Diagnostic{
				Severity: diag.Error,
				Summary:  "Invalid value for the field",
				Detail:   fmt.Sprintf("Invalid user permission, got %s", inputValue),
			},
		}
	}

	return nil
}
